package com.example.demo.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "APP_VW_PERSONA")
public class AppVwPersona {
	
	@Column(name = "id_pais", length = 4)
	private String id_pais;
	
	@Id
	private String id_persona;

	@Column
	private String ID_SALUDO;
	@Column
	private String APELLIDO;
	@Column
	private String STD_N_MAIDEN_NAME;
	@Column
	private String NOMBRES;
	@Column
	private String NOMBRE_GLOBAL;
	@Column
	private String GENERO;
	@Column
	private String GENERO_ESP;
	@Column
	private String GENERO_ENG;
	@Column
	private String GENERO_BRA;
	@Column
	private String GENERO_GER;
	@Column
	private String FECHA_NACIMIENTO;
	@Column
	private String EDAD;
	@Column
	private String TIPO_DOCUMENTO;
	@Column
	private String TIPO_DOCUMENTO_ESP;
	@Column
	private String TIPO_DOCUMENTO_ENG;
	@Column
	private String TIPO_DOCUMENTO_BRA;
	@Column
	private String TIPO_DOCUMENTO_GER;
	@Column
	private String NUMERO_DOCUMENTO;
	@Column
	private String CUIL;
	@Column
	private String ID_ESTADO_CIVIL;
	@Column
	private String ESTADO_CIVIL_ESP;
	@Column
	private String ESTADO_CIVIL_ENG;
	@Column
	private String ESTADO_CIVIL_BRA;
	@Column
	private String ESTADO_CIVIL_GER;
	@Column
	private String ID_NACIONALIDAD;
	@Column
	private String NACIONALIDAD_ESP;
	@Column
	private String NACIONALIDAD_ENG;
	@Column
	private String NACIONALIDAD_BRA;
	@Column
	private String NACIONALIDAD_GER;
	@Column
	private String ID_PAIS_NACIMIENTO;
	@Column
	private String PAIS_NACIMIENTO_ESP;
	@Column
	private String PAIS_NACIMIENTO_ENG;
	@Column
	private String PAIS_NACIMIENTO_BRA;
	@Column
	private String PAIS_NACIMIENTO_GER;
	@Column
	private String ID_PROVINCIA_NACIMIENTO;
	@Column
	private String PROVINCIA_NACIMIENTO_ESP;
	@Column
	private String PROVINCIA_NACIMIENTO_ENG;
	@Column
	private String PROVINCIA_NACIMIENTO_BRA;
	@Column
	private String PROVINCIA_NACIMIENTO_GER;
	@Column
	private String ID_MUNICIPIO_NACIMIENTO;
	@Column
	private String MUNICIPIO_NACIMIENTO_ESP;
	@Column
	private String MUNICIPIO_NACIMIENTO_ENG;
	@Column
	private String MUNICIPIO_NACIMIENTO_BRA;
	@Column
	private String MUNICIPIO_NACIMIENTO_GER;
	@Column
	private String ID_LOCALIDAD_NACIMIENTO;
	@Column
	private String LOCALIDAD_NACIMIENTO_ESP;
	@Column
	private String LOCALIDAD_NACIMIENTO_ENG;
	@Column
	private String LOCALIDAD_NACIMIENTO_BRA;
	@Column
	private String LOCALIDAD_NACIMIENTO_GER;

	public AppVwPersona(String id_pais, String id_persona, String iD_SALUDO, String aPELLIDO,
			String sTD_N_MAIDEN_NAME, String nOMBRES, String nOMBRE_GLOBAL, String gENERO, String gENERO_ESP,
			String gENERO_ENG, String gENERO_BRA, String gENERO_GER, String fECHA_NACIMIENTO, String eDAD,
			String tIPO_DOCUMENTO, String tIPO_DOCUMENTO_ESP, String tIPO_DOCUMENTO_ENG, String tIPO_DOCUMENTO_BRA,
			String tIPO_DOCUMENTO_GER, String nUMERO_DOCUMENTO, String cUIL, String iD_ESTADO_CIVIL,
			String eSTADO_CIVIL_ESP, String eSTADO_CIVIL_ENG, String eSTADO_CIVIL_BRA, String eSTADO_CIVIL_GER,
			String iD_NACIONALIDAD, String nACIONALIDAD_ESP, String nACIONALIDAD_ENG, String nACIONALIDAD_BRA,
			String nACIONALIDAD_GER, String iD_PAIS_NACIMIENTO, String pAIS_NACIMIENTO_ESP, String pAIS_NACIMIENTO_ENG,
			String pAIS_NACIMIENTO_BRA, String pAIS_NACIMIENTO_GER, String iD_PROVINCIA_NACIMIENTO,
			String pROVINCIA_NACIMIENTO_ESP, String pROVINCIA_NACIMIENTO_ENG, String pROVINCIA_NACIMIENTO_BRA,
			String pROVINCIA_NACIMIENTO_GER, String iD_MUNICIPIO_NACIMIENTO, String mUNICIPIO_NACIMIENTO_ESP,
			String mUNICIPIO_NACIMIENTO_ENG, String mUNICIPIO_NACIMIENTO_BRA, String mUNICIPIO_NACIMIENTO_GER,
			String iD_LOCALIDAD_NACIMIENTO, String lOCALIDAD_NACIMIENTO_ESP, String lOCALIDAD_NACIMIENTO_ENG,
			String lOCALIDAD_NACIMIENTO_BRA, String lOCALIDAD_NACIMIENTO_GER) {
		this.id_pais = id_pais;
		this.id_persona = id_persona;
		ID_SALUDO = iD_SALUDO;
		APELLIDO = aPELLIDO;
		STD_N_MAIDEN_NAME = sTD_N_MAIDEN_NAME;
		NOMBRES = nOMBRES;
		NOMBRE_GLOBAL = nOMBRE_GLOBAL;
		GENERO = gENERO;
		GENERO_ESP = gENERO_ESP;
		GENERO_ENG = gENERO_ENG;
		GENERO_BRA = gENERO_BRA;
		GENERO_GER = gENERO_GER;
		FECHA_NACIMIENTO = fECHA_NACIMIENTO;
		EDAD = eDAD;
		TIPO_DOCUMENTO = tIPO_DOCUMENTO;
		TIPO_DOCUMENTO_ESP = tIPO_DOCUMENTO_ESP;
		TIPO_DOCUMENTO_ENG = tIPO_DOCUMENTO_ENG;
		TIPO_DOCUMENTO_BRA = tIPO_DOCUMENTO_BRA;
		TIPO_DOCUMENTO_GER = tIPO_DOCUMENTO_GER;
		NUMERO_DOCUMENTO = nUMERO_DOCUMENTO;
		CUIL = cUIL;
		ID_ESTADO_CIVIL = iD_ESTADO_CIVIL;
		ESTADO_CIVIL_ESP = eSTADO_CIVIL_ESP;
		ESTADO_CIVIL_ENG = eSTADO_CIVIL_ENG;
		ESTADO_CIVIL_BRA = eSTADO_CIVIL_BRA;
		ESTADO_CIVIL_GER = eSTADO_CIVIL_GER;
		ID_NACIONALIDAD = iD_NACIONALIDAD;
		NACIONALIDAD_ESP = nACIONALIDAD_ESP;
		NACIONALIDAD_ENG = nACIONALIDAD_ENG;
		NACIONALIDAD_BRA = nACIONALIDAD_BRA;
		NACIONALIDAD_GER = nACIONALIDAD_GER;
		ID_PAIS_NACIMIENTO = iD_PAIS_NACIMIENTO;
		PAIS_NACIMIENTO_ESP = pAIS_NACIMIENTO_ESP;
		PAIS_NACIMIENTO_ENG = pAIS_NACIMIENTO_ENG;
		PAIS_NACIMIENTO_BRA = pAIS_NACIMIENTO_BRA;
		PAIS_NACIMIENTO_GER = pAIS_NACIMIENTO_GER;
		ID_PROVINCIA_NACIMIENTO = iD_PROVINCIA_NACIMIENTO;
		PROVINCIA_NACIMIENTO_ESP = pROVINCIA_NACIMIENTO_ESP;
		PROVINCIA_NACIMIENTO_ENG = pROVINCIA_NACIMIENTO_ENG;
		PROVINCIA_NACIMIENTO_BRA = pROVINCIA_NACIMIENTO_BRA;
		PROVINCIA_NACIMIENTO_GER = pROVINCIA_NACIMIENTO_GER;
		ID_MUNICIPIO_NACIMIENTO = iD_MUNICIPIO_NACIMIENTO;
		MUNICIPIO_NACIMIENTO_ESP = mUNICIPIO_NACIMIENTO_ESP;
		MUNICIPIO_NACIMIENTO_ENG = mUNICIPIO_NACIMIENTO_ENG;
		MUNICIPIO_NACIMIENTO_BRA = mUNICIPIO_NACIMIENTO_BRA;
		MUNICIPIO_NACIMIENTO_GER = mUNICIPIO_NACIMIENTO_GER;
		ID_LOCALIDAD_NACIMIENTO = iD_LOCALIDAD_NACIMIENTO;
		LOCALIDAD_NACIMIENTO_ESP = lOCALIDAD_NACIMIENTO_ESP;
		LOCALIDAD_NACIMIENTO_ENG = lOCALIDAD_NACIMIENTO_ENG;
		LOCALIDAD_NACIMIENTO_BRA = lOCALIDAD_NACIMIENTO_BRA;
		LOCALIDAD_NACIMIENTO_GER = lOCALIDAD_NACIMIENTO_GER;
	}	
	

	public AppVwPersona() {
	}
	
	public String getId_pais() {
		return id_pais;
	}

	public void setId_pais(String id_pais) {
		this.id_pais = id_pais;
	}

	public String getId_persona() {
		return id_persona;
	}

	public void setId_persona(String id_persona) {
		this.id_persona = id_persona;
	}

	public String getID_SALUDO() {
		return ID_SALUDO;
	}

	public void setID_SALUDO(String iD_SALUDO) {
		ID_SALUDO = iD_SALUDO;
	}

	public String getAPELLIDO() {
		return APELLIDO;
	}

	public void setAPELLIDO(String aPELLIDO) {
		APELLIDO = aPELLIDO;
	}

	public String getSTD_N_MAIDEN_NAME() {
		return STD_N_MAIDEN_NAME;
	}

	public void setSTD_N_MAIDEN_NAME(String sTD_N_MAIDEN_NAME) {
		STD_N_MAIDEN_NAME = sTD_N_MAIDEN_NAME;
	}

	public String getNOMBRES() {
		return NOMBRES;
	}

	public void setNOMBRES(String nOMBRES) {
		NOMBRES = nOMBRES;
	}

	public String getNOMBRE_GLOBAL() {
		return NOMBRE_GLOBAL;
	}

	public void setNOMBRE_GLOBAL(String nOMBRE_GLOBAL) {
		NOMBRE_GLOBAL = nOMBRE_GLOBAL;
	}

	public String getGENERO() {
		return GENERO;
	}

	public void setGENERO(String gENERO) {
		GENERO = gENERO;
	}

	public String getGENERO_ESP() {
		return GENERO_ESP;
	}

	public void setGENERO_ESP(String gENERO_ESP) {
		GENERO_ESP = gENERO_ESP;
	}

	public String getGENERO_ENG() {
		return GENERO_ENG;
	}

	public void setGENERO_ENG(String gENERO_ENG) {
		GENERO_ENG = gENERO_ENG;
	}

	public String getGENERO_BRA() {
		return GENERO_BRA;
	}

	public void setGENERO_BRA(String gENERO_BRA) {
		GENERO_BRA = gENERO_BRA;
	}

	public String getGENERO_GER() {
		return GENERO_GER;
	}

	public void setGENERO_GER(String gENERO_GER) {
		GENERO_GER = gENERO_GER;
	}

	public String getFECHA_NACIMIENTO() {
		return FECHA_NACIMIENTO;
	}

	public void setFECHA_NACIMIENTO(String fECHA_NACIMIENTO) {
		FECHA_NACIMIENTO = fECHA_NACIMIENTO;
	}

	public String getEDAD() {
		return EDAD;
	}

	public void setEDAD(String eDAD) {
		EDAD = eDAD;
	}

	public String getTIPO_DOCUMENTO() {
		return TIPO_DOCUMENTO;
	}

	public void setTIPO_DOCUMENTO(String tIPO_DOCUMENTO) {
		TIPO_DOCUMENTO = tIPO_DOCUMENTO;
	}

	public String getTIPO_DOCUMENTO_ESP() {
		return TIPO_DOCUMENTO_ESP;
	}

	public void setTIPO_DOCUMENTO_ESP(String tIPO_DOCUMENTO_ESP) {
		TIPO_DOCUMENTO_ESP = tIPO_DOCUMENTO_ESP;
	}

	public String getTIPO_DOCUMENTO_ENG() {
		return TIPO_DOCUMENTO_ENG;
	}

	public void setTIPO_DOCUMENTO_ENG(String tIPO_DOCUMENTO_ENG) {
		TIPO_DOCUMENTO_ENG = tIPO_DOCUMENTO_ENG;
	}

	public String getTIPO_DOCUMENTO_BRA() {
		return TIPO_DOCUMENTO_BRA;
	}

	public void setTIPO_DOCUMENTO_BRA(String tIPO_DOCUMENTO_BRA) {
		TIPO_DOCUMENTO_BRA = tIPO_DOCUMENTO_BRA;
	}

	public String getTIPO_DOCUMENTO_GER() {
		return TIPO_DOCUMENTO_GER;
	}

	public void setTIPO_DOCUMENTO_GER(String tIPO_DOCUMENTO_GER) {
		TIPO_DOCUMENTO_GER = tIPO_DOCUMENTO_GER;
	}

	public String getNUMERO_DOCUMENTO() {
		return NUMERO_DOCUMENTO;
	}

	public void setNUMERO_DOCUMENTO(String nUMERO_DOCUMENTO) {
		NUMERO_DOCUMENTO = nUMERO_DOCUMENTO;
	}

	public String getCUIL() {
		return CUIL;
	}

	public void setCUIL(String cUIL) {
		CUIL = cUIL;
	}

	public String getID_ESTADO_CIVIL() {
		return ID_ESTADO_CIVIL;
	}

	public void setID_ESTADO_CIVIL(String iD_ESTADO_CIVIL) {
		ID_ESTADO_CIVIL = iD_ESTADO_CIVIL;
	}

	public String getESTADO_CIVIL_ESP() {
		return ESTADO_CIVIL_ESP;
	}

	public void setESTADO_CIVIL_ESP(String eSTADO_CIVIL_ESP) {
		ESTADO_CIVIL_ESP = eSTADO_CIVIL_ESP;
	}

	public String getESTADO_CIVIL_ENG() {
		return ESTADO_CIVIL_ENG;
	}

	public void setESTADO_CIVIL_ENG(String eSTADO_CIVIL_ENG) {
		ESTADO_CIVIL_ENG = eSTADO_CIVIL_ENG;
	}

	public String getESTADO_CIVIL_BRA() {
		return ESTADO_CIVIL_BRA;
	}

	public void setESTADO_CIVIL_BRA(String eSTADO_CIVIL_BRA) {
		ESTADO_CIVIL_BRA = eSTADO_CIVIL_BRA;
	}

	public String getESTADO_CIVIL_GER() {
		return ESTADO_CIVIL_GER;
	}

	public void setESTADO_CIVIL_GER(String eSTADO_CIVIL_GER) {
		ESTADO_CIVIL_GER = eSTADO_CIVIL_GER;
	}

	public String getID_NACIONALIDAD() {
		return ID_NACIONALIDAD;
	}

	public void setID_NACIONALIDAD(String iD_NACIONALIDAD) {
		ID_NACIONALIDAD = iD_NACIONALIDAD;
	}

	public String getNACIONALIDAD_ESP() {
		return NACIONALIDAD_ESP;
	}

	public void setNACIONALIDAD_ESP(String nACIONALIDAD_ESP) {
		NACIONALIDAD_ESP = nACIONALIDAD_ESP;
	}

	public String getNACIONALIDAD_ENG() {
		return NACIONALIDAD_ENG;
	}

	public void setNACIONALIDAD_ENG(String nACIONALIDAD_ENG) {
		NACIONALIDAD_ENG = nACIONALIDAD_ENG;
	}

	public String getNACIONALIDAD_BRA() {
		return NACIONALIDAD_BRA;
	}

	public void setNACIONALIDAD_BRA(String nACIONALIDAD_BRA) {
		NACIONALIDAD_BRA = nACIONALIDAD_BRA;
	}

	public String getNACIONALIDAD_GER() {
		return NACIONALIDAD_GER;
	}

	public void setNACIONALIDAD_GER(String nACIONALIDAD_GER) {
		NACIONALIDAD_GER = nACIONALIDAD_GER;
	}

	public String getID_PAIS_NACIMIENTO() {
		return ID_PAIS_NACIMIENTO;
	}

	public void setID_PAIS_NACIMIENTO(String iD_PAIS_NACIMIENTO) {
		ID_PAIS_NACIMIENTO = iD_PAIS_NACIMIENTO;
	}

	public String getPAIS_NACIMIENTO_ESP() {
		return PAIS_NACIMIENTO_ESP;
	}

	public void setPAIS_NACIMIENTO_ESP(String pAIS_NACIMIENTO_ESP) {
		PAIS_NACIMIENTO_ESP = pAIS_NACIMIENTO_ESP;
	}

	public String getPAIS_NACIMIENTO_ENG() {
		return PAIS_NACIMIENTO_ENG;
	}

	public void setPAIS_NACIMIENTO_ENG(String pAIS_NACIMIENTO_ENG) {
		PAIS_NACIMIENTO_ENG = pAIS_NACIMIENTO_ENG;
	}

	public String getPAIS_NACIMIENTO_BRA() {
		return PAIS_NACIMIENTO_BRA;
	}

	public void setPAIS_NACIMIENTO_BRA(String pAIS_NACIMIENTO_BRA) {
		PAIS_NACIMIENTO_BRA = pAIS_NACIMIENTO_BRA;
	}

	public String getPAIS_NACIMIENTO_GER() {
		return PAIS_NACIMIENTO_GER;
	}

	public void setPAIS_NACIMIENTO_GER(String pAIS_NACIMIENTO_GER) {
		PAIS_NACIMIENTO_GER = pAIS_NACIMIENTO_GER;
	}

	public String getID_PROVINCIA_NACIMIENTO() {
		return ID_PROVINCIA_NACIMIENTO;
	}

	public void setID_PROVINCIA_NACIMIENTO(String iD_PROVINCIA_NACIMIENTO) {
		ID_PROVINCIA_NACIMIENTO = iD_PROVINCIA_NACIMIENTO;
	}

	public String getPROVINCIA_NACIMIENTO_ESP() {
		return PROVINCIA_NACIMIENTO_ESP;
	}

	public void setPROVINCIA_NACIMIENTO_ESP(String pROVINCIA_NACIMIENTO_ESP) {
		PROVINCIA_NACIMIENTO_ESP = pROVINCIA_NACIMIENTO_ESP;
	}

	public String getPROVINCIA_NACIMIENTO_ENG() {
		return PROVINCIA_NACIMIENTO_ENG;
	}

	public void setPROVINCIA_NACIMIENTO_ENG(String pROVINCIA_NACIMIENTO_ENG) {
		PROVINCIA_NACIMIENTO_ENG = pROVINCIA_NACIMIENTO_ENG;
	}

	public String getPROVINCIA_NACIMIENTO_BRA() {
		return PROVINCIA_NACIMIENTO_BRA;
	}

	public void setPROVINCIA_NACIMIENTO_BRA(String pROVINCIA_NACIMIENTO_BRA) {
		PROVINCIA_NACIMIENTO_BRA = pROVINCIA_NACIMIENTO_BRA;
	}

	public String getPROVINCIA_NACIMIENTO_GER() {
		return PROVINCIA_NACIMIENTO_GER;
	}

	public void setPROVINCIA_NACIMIENTO_GER(String pROVINCIA_NACIMIENTO_GER) {
		PROVINCIA_NACIMIENTO_GER = pROVINCIA_NACIMIENTO_GER;
	}

	public String getID_MUNICIPIO_NACIMIENTO() {
		return ID_MUNICIPIO_NACIMIENTO;
	}

	public void setID_MUNICIPIO_NACIMIENTO(String iD_MUNICIPIO_NACIMIENTO) {
		ID_MUNICIPIO_NACIMIENTO = iD_MUNICIPIO_NACIMIENTO;
	}

	public String getMUNICIPIO_NACIMIENTO_ESP() {
		return MUNICIPIO_NACIMIENTO_ESP;
	}

	public void setMUNICIPIO_NACIMIENTO_ESP(String mUNICIPIO_NACIMIENTO_ESP) {
		MUNICIPIO_NACIMIENTO_ESP = mUNICIPIO_NACIMIENTO_ESP;
	}

	public String getMUNICIPIO_NACIMIENTO_ENG() {
		return MUNICIPIO_NACIMIENTO_ENG;
	}

	public void setMUNICIPIO_NACIMIENTO_ENG(String mUNICIPIO_NACIMIENTO_ENG) {
		MUNICIPIO_NACIMIENTO_ENG = mUNICIPIO_NACIMIENTO_ENG;
	}

	public String getMUNICIPIO_NACIMIENTO_BRA() {
		return MUNICIPIO_NACIMIENTO_BRA;
	}

	public void setMUNICIPIO_NACIMIENTO_BRA(String mUNICIPIO_NACIMIENTO_BRA) {
		MUNICIPIO_NACIMIENTO_BRA = mUNICIPIO_NACIMIENTO_BRA;
	}

	public String getMUNICIPIO_NACIMIENTO_GER() {
		return MUNICIPIO_NACIMIENTO_GER;
	}

	public void setMUNICIPIO_NACIMIENTO_GER(String mUNICIPIO_NACIMIENTO_GER) {
		MUNICIPIO_NACIMIENTO_GER = mUNICIPIO_NACIMIENTO_GER;
	}

	public String getID_LOCALIDAD_NACIMIENTO() {
		return ID_LOCALIDAD_NACIMIENTO;
	}

	public void setID_LOCALIDAD_NACIMIENTO(String iD_LOCALIDAD_NACIMIENTO) {
		ID_LOCALIDAD_NACIMIENTO = iD_LOCALIDAD_NACIMIENTO;
	}

	public String getLOCALIDAD_NACIMIENTO_ESP() {
		return LOCALIDAD_NACIMIENTO_ESP;
	}

	public void setLOCALIDAD_NACIMIENTO_ESP(String lOCALIDAD_NACIMIENTO_ESP) {
		LOCALIDAD_NACIMIENTO_ESP = lOCALIDAD_NACIMIENTO_ESP;
	}

	public String getLOCALIDAD_NACIMIENTO_ENG() {
		return LOCALIDAD_NACIMIENTO_ENG;
	}

	public void setLOCALIDAD_NACIMIENTO_ENG(String lOCALIDAD_NACIMIENTO_ENG) {
		LOCALIDAD_NACIMIENTO_ENG = lOCALIDAD_NACIMIENTO_ENG;
	}

	public String getLOCALIDAD_NACIMIENTO_BRA() {
		return LOCALIDAD_NACIMIENTO_BRA;
	}

	public void setLOCALIDAD_NACIMIENTO_BRA(String lOCALIDAD_NACIMIENTO_BRA) {
		LOCALIDAD_NACIMIENTO_BRA = lOCALIDAD_NACIMIENTO_BRA;
	}

	public String getLOCALIDAD_NACIMIENTO_GER() {
		return LOCALIDAD_NACIMIENTO_GER;
	}

	public void setLOCALIDAD_NACIMIENTO_GER(String lOCALIDAD_NACIMIENTO_GER) {
		LOCALIDAD_NACIMIENTO_GER = lOCALIDAD_NACIMIENTO_GER;
	}

	@Override
	public String toString() {
		return "AppVwPersona [id_pais=" + id_pais + ", id_persona=" + id_persona + ", ID_SALUDO="
				+ ID_SALUDO + ", APELLIDO=" + APELLIDO + ", STD_N_MAIDEN_NAME=" + STD_N_MAIDEN_NAME + ", NOMBRES="
				+ NOMBRES + ", NOMBRE_GLOBAL=" + NOMBRE_GLOBAL + ", GENERO=" + GENERO + ", GENERO_ESP=" + GENERO_ESP
				+ ", GENERO_ENG=" + GENERO_ENG + ", GENERO_BRA=" + GENERO_BRA + ", GENERO_GER=" + GENERO_GER
				+ ", FECHA_NACIMIENTO=" + FECHA_NACIMIENTO + ", EDAD=" + EDAD + ", TIPO_DOCUMENTO=" + TIPO_DOCUMENTO
				+ ", TIPO_DOCUMENTO_ESP=" + TIPO_DOCUMENTO_ESP + ", TIPO_DOCUMENTO_ENG=" + TIPO_DOCUMENTO_ENG
				+ ", TIPO_DOCUMENTO_BRA=" + TIPO_DOCUMENTO_BRA + ", TIPO_DOCUMENTO_GER=" + TIPO_DOCUMENTO_GER
				+ ", NUMERO_DOCUMENTO=" + NUMERO_DOCUMENTO + ", CUIL=" + CUIL + ", ID_ESTADO_CIVIL=" + ID_ESTADO_CIVIL
				+ ", ESTADO_CIVIL_ESP=" + ESTADO_CIVIL_ESP + ", ESTADO_CIVIL_ENG=" + ESTADO_CIVIL_ENG
				+ ", ESTADO_CIVIL_BRA=" + ESTADO_CIVIL_BRA + ", ESTADO_CIVIL_GER=" + ESTADO_CIVIL_GER
				+ ", ID_NACIONALIDAD=" + ID_NACIONALIDAD + ", NACIONALIDAD_ESP=" + NACIONALIDAD_ESP
				+ ", NACIONALIDAD_ENG=" + NACIONALIDAD_ENG + ", NACIONALIDAD_BRA=" + NACIONALIDAD_BRA
				+ ", NACIONALIDAD_GER=" + NACIONALIDAD_GER + ", ID_PAIS_NACIMIENTO=" + ID_PAIS_NACIMIENTO
				+ ", PAIS_NACIMIENTO_ESP=" + PAIS_NACIMIENTO_ESP + ", PAIS_NACIMIENTO_ENG=" + PAIS_NACIMIENTO_ENG
				+ ", PAIS_NACIMIENTO_BRA=" + PAIS_NACIMIENTO_BRA + ", PAIS_NACIMIENTO_GER=" + PAIS_NACIMIENTO_GER
				+ ", ID_PROVINCIA_NACIMIENTO=" + ID_PROVINCIA_NACIMIENTO + ", PROVINCIA_NACIMIENTO_ESP="
				+ PROVINCIA_NACIMIENTO_ESP + ", PROVINCIA_NACIMIENTO_ENG=" + PROVINCIA_NACIMIENTO_ENG
				+ ", PROVINCIA_NACIMIENTO_BRA=" + PROVINCIA_NACIMIENTO_BRA + ", PROVINCIA_NACIMIENTO_GER="
				+ PROVINCIA_NACIMIENTO_GER + ", ID_MUNICIPIO_NACIMIENTO=" + ID_MUNICIPIO_NACIMIENTO
				+ ", MUNICIPIO_NACIMIENTO_ESP=" + MUNICIPIO_NACIMIENTO_ESP + ", MUNICIPIO_NACIMIENTO_ENG="
				+ MUNICIPIO_NACIMIENTO_ENG + ", MUNICIPIO_NACIMIENTO_BRA=" + MUNICIPIO_NACIMIENTO_BRA
				+ ", MUNICIPIO_NACIMIENTO_GER=" + MUNICIPIO_NACIMIENTO_GER + ", ID_LOCALIDAD_NACIMIENTO="
				+ ID_LOCALIDAD_NACIMIENTO + ", LOCALIDAD_NACIMIENTO_ESP=" + LOCALIDAD_NACIMIENTO_ESP
				+ ", LOCALIDAD_NACIMIENTO_ENG=" + LOCALIDAD_NACIMIENTO_ENG + ", LOCALIDAD_NACIMIENTO_BRA="
				+ LOCALIDAD_NACIMIENTO_BRA + ", LOCALIDAD_NACIMIENTO_GER=" + LOCALIDAD_NACIMIENTO_GER + "]";
	}
	
	
}
